from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
API_SRC = ROOT / "services" / "api" / "src"
SCHEMA_PATH = Path(__file__).resolve().parent / "schema" / "connector-message-v1.schema.json"

sys.path.insert(0, str(API_SRC))

from moodmusic_api.connector_protocol import (
    PROTOCOL_VERSION,
    SUPPORTED_CAPABILITIES,
    SUPPORTED_CONNECTOR_TYPES,
    connector_message_json_schema,
    connector_protocol_descriptor,
)

EXTENSION_CONTRACT_PATH = (
    ROOT / "extensions" / "qqmusic-web-connector" / "connector-contract.js"
)


def main() -> None:
    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    schema = connector_message_json_schema()
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema["$id"] = "https://moodmusic.local/contracts/connector-message-v1.schema.json"
    schema["title"] = "MoodMusic Connector Message v1"
    SCHEMA_PATH.write_text(
        json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    descriptor = connector_protocol_descriptor()
    extension_contract = (
        "// Generated by packages/contracts/generate_connector_schema.py. Do not edit.\n"
        f"export const PROTOCOL_VERSION = {json.dumps(PROTOCOL_VERSION)};\n"
        "export const CONNECTOR_TYPES = Object.freeze("
        f"{json.dumps(list(SUPPORTED_CONNECTOR_TYPES))});\n"
        "export const CONNECTOR_CAPABILITIES = Object.freeze("
        f"{json.dumps(list(SUPPORTED_CAPABILITIES))});\n"
        "export const CONNECTOR_MESSAGE_TYPES = Object.freeze("
        f"{json.dumps(descriptor.messageTypes)});\n"
    )
    EXTENSION_CONTRACT_PATH.write_text(extension_contract, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
